-- Revised by oleh5230, 24.06.24
-- Original script by Qudix
-- Last edit: 28.02.26

local opt_aim_rattle = true
local opt_lower_raise_rattle = true
local opt_sprint_rattle = true
local volume_aim_rattle = 1
local volume_lower_raise_rattle = 1
local volume_sprint_rattle = 1

gamma = true

wpn_kinds = {
    ["w_pistol"]            = "pistol-0",
    ["w_smg"]               = "smg-0",
    ["w_shotgun"]           = "shotgun-0",
    ["w_rifle"]             = "rifle-0",
    ["w_sniper"]            = "shotgun-0",
    ["w_explosive"]         = "shotgun-0",
    ["w_misc"]              = "shotgun-0",
}

-- create sample queues to mitigate the issue of same sample playing multiple times in a row
queues = {}
count = {}
limit = {
    ["pistol-0"]            = 9,
    ["smg-0"]               = 9,
    ["shotgun-0"]           = 9,
    ["rifle-0"]             = 9,
    ["sprint_pistol-0"]     = 6,
    ["sprint_smg-0"]        = 6,
    ["sprint_shotgun-0"]    = 6,
    ["sprint_rifle-0"]      = 6,

    ["mp7\\mp7-0"]          = 8,
    ["db\\db_shotty-0"]     = 8,
    ["asval\\asval-0"]      = 8,
    ["mk14\\mk14-0"]        = 8,
    ["pkm\\pkm-0"]          = 8,
    ["sprint_pkm\\pkm-0"]   = 16,
    ["m82\\m82-0"]          = 8,
}

local function init()
    for k,v in pairs(limit) do
        queues[k] = {}
        count[k] = 1
    end

    for k,v in pairs(queues) do
        for i=1, limit[k] do
            table.insert(queues[k], i)
        end
        shuffle_table(queues[k])
    end
end

local cached_sec
local ini_cas = ini_file_ex("plugins\\grok_casings_sounds_weapons.ltx")
local wpn = {
    weight = 3.3,
    aim_time = 0.25,
    volume = 0.5,
    frequency = 1,
    kind = "w_rifle",
    class = "rifle-0",
    sclass = "sprint_rifle-0",
}
function get_wpn_params(weapon)
    if not weapon then return end
    local sec = weapon:section()
    sec = SYS_GetParam(0, sec, "parent_section") or sec
    if not cached_sec or sec ~= cached_sec then
        cached_sec     = sec
        wpn.weight     = ini_sys:r_string_ex(sec, "inv_weight") or 3.3
        wpn.aim_time   = ini_sys:r_string_ex(sec, "zoom_rotate_time") or 0.25
        wpn.volume     = 0.5 --(0.25 + weight * 0.025)
        wpn.frequency  = clamp(0.25 / wpn.aim_time, 0.8, 1.2)
        wpn.kind       = SYS_GetParam(0, sec, "kind") or "w_misc"
        wpn.class      = wpn_kinds[wpn.kind] or wpn_kinds["w_misc"]

        -- special case for magazine fed shotguns
        -- reads GAMMA casings sounds .ltx to check if weapon has delayed ejection (manual action)
        if wpn.kind == "w_shotgun" and
        not ini_cas:r_float_ex(sec, "eject_delay") and
        SYS_GetParam(0, sec, "tri_state_reload", "off") ~= "on" and
        SYS_GetParam(0, sec, "class", "WP_ASHTG") ~= "WP_BM16" then
            wpn.class = wpn_kinds["w_rifle"]
        end

        -- special case for self loading snipers
        -- reads GAMMA casings sounds .ltx to check if weapon has delayed ejection (manual action)
        if wpn.kind == "w_sniper" and
        not ini_cas:r_float_ex(sec, "eject_delay") then
            wpn.class = wpn_kinds["w_rifle"]
        end

        wpn.class  = SYS_GetParam(0, sec, "snd_rattle_class", wpn.class)
        wpn.sclass = queues["sprint_"..wpn.class] and "sprint_"..wpn.class or wpn.class
    end
end

function play_aim_sound(volume, frequency, weapon)
    if not wpn.class or not count[wpn.class] or not limit[wpn.class] then
        printe("!ERROR eft_rattle | missing weapon parameters: %s %s %s", wpn.sclass, count[wpn.sclass], limit[wpn.sclass])
    return end

    if weapon then get_wpn_params(weapon)
    else
        local active_item = db.actor:active_item()
        if not active_item then return end
        if not IsWeapon(active_item) or IsMelee(active_item) then return end
        get_wpn_params(active_item)
    end

    local sound = sound_object("weapons\\_rattle\\" .. wpn.class .. queues[wpn.class][count[wpn.class]])
    sound:play(db.actor, 0, sound_object.s2d)
    sound.volume = (wpn.volume * volume) or 0.5
    sound.frequency = frequency or 1
    --printf("[eft_rattle] %s | volume: %s, frequency: %s", wpn.class .. queues[wpn.class][count[wpn.class]], volume, frequency)

    count[wpn.class] = count[wpn.class] + 1
    if count[wpn.class] > limit[wpn.class] then
        count[wpn.class] = 1
        shuffle_table(queues[wpn.class])
    end
end

function play_sprint_rattle_sound(volume, frequency, weapon)
    if not wpn.sclass or not count[wpn.sclass] or not limit[wpn.sclass] then
        printe("!ERROR eft_rattle | missing weapon parameters: %s %s %s", wpn.sclass, count[wpn.sclass], limit[wpn.sclass])
    return end

    if weapon then get_wpn_params(weapon)
    else
        local active_item = db.actor:active_item()
        if not active_item then return end
        if not IsWeapon(active_item) or IsMelee(active_item) then return end
        get_wpn_params(active_item)
    end

    local sound = sound_object("weapons\\_rattle\\" .. wpn.sclass .. queues[wpn.sclass][count[wpn.sclass]])
    sound:play(db.actor, 0, sound_object.s2d)
    sound.volume = (wpn.volume * volume) or 0.5
    sound.frequency = frequency or 1
    --printf("[eft_rattle] %s | volume: %s, frequency: %s", wpn.sclass .. queues[wpn.sclass][count[wpn.sclass]], volume, frequency)

    count[wpn.sclass] = count[wpn.sclass] + 1
    if count[wpn.sclass] > limit[wpn.sclass] then
        count[wpn.sclass] = 1
        shuffle_table(queues[wpn.sclass])
    end
end

function actor_on_weapon_zoom_in(weapon)
    if opt_aim_rattle then
        play_aim_sound(volume_aim_rattle * 0.8, wpn.frequency, weapon)
    end
end

function actor_on_weapon_zoom_out(weapon)
    if opt_aim_rattle then
        play_aim_sound(volume_aim_rattle * 0.8, wpn.frequency, weapon)
    end
end

function actor_on_weapon_zoom_type_changed(weapon, previous, current)
    if opt_aim_rattle then
        -- UBGL on
        if current == 2 then
            play_aim_sound(volume_aim_rattle * 0.6, wpn.frequency, weapon)
        -- UBGL off
        elseif previous == 2 then
            play_aim_sound(volume_aim_rattle * 0.6, wpn.frequency, weapon)
        -- alt aim on
        elseif current == 1 and axr_main.weapon_is_zoomed then
            play_aim_sound(volume_aim_rattle * 0.6, wpn.frequency, weapon)
        -- alt aim off
        elseif current == 0 and axr_main.weapon_is_zoomed then
            play_aim_sound(volume_aim_rattle * 0.6, wpn.frequency, weapon)
        end
    end
end

function actor_on_weapon_raise(weapon)
    if opt_lower_raise_rattle then
        play_aim_sound(volume_lower_raise_rattle, 1, weapon)
    end
end

function actor_on_weapon_lower(weapon)
    if opt_lower_raise_rattle then
        play_aim_sound(volume_lower_raise_rattle, 1, weapon)
    end
end

local wct_raised = false
play_sound = weapon_cover_tilt_rattle.play_sound
function weapon_cover_tilt_rattle.play_sound(dir, weapon, coeff)
    if not weapon_cover_tilt.get_setting("tilt_rattle") or not weapon then return end

    if wct_raised then
        play_aim_sound(volume_lower_raise_rattle, clamp(1.25 - wpn.weight * 0.0625, 0.8, 1.2), weapon)
    else
        play_aim_sound(volume_lower_raise_rattle, clamp(1.25 - wpn.weight * 0.0625, 0.8, 1.2), weapon)
    end
    wct_raised = not wct_raised
end

function actor_on_footstep(material, power, hud_view, flags)
    -- footstep callback is being sent upon landing (sometimes even twice)
    if oleh_sound_utils and oleh_sound_utils.land_tg and oleh_sound_utils.land_tg + 200 > time_global() then return end

    local active_item = db.actor:active_item()
    if not active_item then return end
    if IsWeapon(active_item) and not IsMelee(active_item) then
        local state = active_item:get_state()

        if opt_sprint_rattle and IsMoveState('mcSprint') and state and state == 0 then -- and game.actor_weapon_lowered()
            play_sprint_rattle_sound(volume_sprint_rattle, 1, active_item)
        end
    end
end

function load_mcm_options()
    if ui_mcm and oleh_sounds_mcm and oleh_sounds_mcm.on_mcm_load then
        opt_aim_rattle              = ui_mcm.get("oleh_sounds/weapons/enabled_aim_rattle")
        opt_lower_raise_rattle      = ui_mcm.get("oleh_sounds/weapons/enabled_lower_raise_rattle")
        opt_sprint_rattle           = ui_mcm.get("oleh_sounds/weapons/enabled_sprint_rattle")
        volume_aim_rattle           = ui_mcm.get("oleh_sounds/weapons/volume_aim_rattle") or 1
        volume_lower_raise_rattle   = ui_mcm.get("oleh_sounds/weapons/volume_lower_raise_rattle") or 1
        volume_sprint_rattle        = ui_mcm.get("oleh_sounds/weapons/volume_sprint_rattle") or 1
    elseif ui_mcm and grok_casings_sounds_mcm and grok_casings_sounds_mcm.on_mcm_load then
        opt_aim_rattle              = ui_mcm.get("grok_casings_sounds/enabled_aim_rattle")
        opt_lower_raise_rattle      = ui_mcm.get("grok_casings_sounds/enabled_lower_raise_rattle")
        opt_sprint_rattle           = ui_mcm.get("grok_casings_sounds/enabled_sprint_rattle")
        volume_aim_rattle           = ui_mcm.get("grok_casings_sounds/volume_aim_rattle") or 1
        volume_lower_raise_rattle   = ui_mcm.get("grok_casings_sounds/volume_lower_raise_rattle") or 1
        volume_sprint_rattle        = ui_mcm.get("grok_casings_sounds/volume_sprint_rattle") or 1
    end
end

function on_game_start()
    init()
    RegisterScriptCallback("actor_on_weapon_zoom_in", actor_on_weapon_zoom_in)
    RegisterScriptCallback("actor_on_weapon_zoom_out", actor_on_weapon_zoom_out)
    RegisterScriptCallback("actor_on_weapon_zoom_type_changed", actor_on_weapon_zoom_type_changed)
    RegisterScriptCallback("actor_on_weapon_raise", actor_on_weapon_raise)
    RegisterScriptCallback("actor_on_weapon_lower", actor_on_weapon_lower)
    RegisterScriptCallback("actor_on_footstep", actor_on_footstep)
    RegisterScriptCallback("on_option_change", load_mcm_options)
    load_mcm_options()
end