-- play unload sound unique to the weapon
Action_Unload = ui_inventory.UIInventory.Action_Unload
ui_inventory.UIInventory.Action_Unload = function(self, obj, bag)

	local itm = obj and self:CheckItem(obj)
	local path = itm and ini_sys:r_string_ex(itm:section(),"snd_unload")
	if path and itms_manager.timeout_snd_on_take then
		itms_manager.timeout_snd_on_take(250)

		local snd = sound_object(path)
		snd:play(db.actor,0,sound_object.s2d)
	end

	Action_Unload(self, obj, bag)
end